### ISSUE TITLE
Scrapped or attached views may not be recycled. isScrap:false isAttached:true

### ISSUE THREAD

**Issue by PhilippeBoisney** [lapism/SearchBar-SearchView#242] opened 2017-02-23 14:30 UTC
It seems that [issue](https://github.com/lapism/SearchView/issues/192) resurfaced a lot in my app...

![image](https://cloud.githubusercontent.com/assets/6847959/23262861/73717848-f9dc-11e6-8f89-8a233a2a1ea5.png)

**This is the complete stacktrace:** 

```
Fatal Exception: java.lang.IllegalArgumentException: Scrapped or attached views may not be recycled. isScrap:false isAttached:true
       at android.support.v7.widget.RecyclerView$Recycler.recycleViewHolderInternal(RecyclerView.java:5659)
       at android.support.v7.widget.RecyclerView$LayoutManager.scrapOrRecycleView(RecyclerView.java:8282)
       at android.support.v7.widget.RecyclerView$LayoutManager.detachAndScrapAttachedViews(RecyclerView.java:8267)
       at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:553)
       at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3506)
       at android.support.v7.widget.RecyclerView.onMeasure(RecyclerView.java:2969)
       at android.view.View.measure(View.java:17915)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5698)
       at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1692)
       at android.widget.LinearLayout.measureVertical(LinearLayout.java:760)
       at android.widget.LinearLayout.onMeasure(LinearLayout.java:629)
       at android.view.View.measure(View.java:17915)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5698)
       at android.widget.FrameLayout.onMeasure(FrameLayout.java:465)
       at android.support.v7.widget.CardView.onMeasure(CardView.java:211)
       at android.view.View.measure(View.java:17915)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5698)
       at android.widget.FrameLayout.onMeasure(FrameLayout.java:465)
       at android.view.View.measure(View.java:17915)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5698)
       at android.support.design.widget.CoordinatorLayout.onMeasureChild(CoordinatorLayout.java:714)
       at android.support.design.widget.CoordinatorLayout.onMeasure(CoordinatorLayout.java:786)
       at android.view.View.measure(View.java:17915)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5698)
       at android.widget.FrameLayout.onMeasure(FrameLayout.java:465)
       at android.view.View.measure(View.java:17915)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5698)
       at android.widget.FrameLayout.onMeasure(FrameLayout.java:465)
       at android.view.View.measure(View.java:17915)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5698)
       at android.support.design.widget.CoordinatorLayout.onMeasureChild(CoordinatorLayout.java:714)
       at android.support.design.widget.CoordinatorLayout.onMeasure(CoordinatorLayout.java:786)
       at android.view.View.measure(View.java:17915)
       at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:846)
       at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:512)
       at android.view.View.measure(View.java:17915)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5698)
       at android.widget.FrameLayout.onMeasure(FrameLayout.java:465)
       at android.support.v7.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:139)
       at android.view.View.measure(View.java:17915)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5698)
       at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1692)
       at android.widget.LinearLayout.measureVertical(LinearLayout.java:760)
       at android.widget.LinearLayout.onMeasure(LinearLayout.java:629)
       at android.view.View.measure(View.java:17915)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5698)
       at android.widget.FrameLayout.onMeasure(FrameLayout.java:465)
       at android.view.View.measure(View.java:17915)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5698)
       at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1692)
       at android.widget.LinearLayout.measureVertical(LinearLayout.java:760)
       at android.widget.LinearLayout.onMeasure(LinearLayout.java:629)
       at android.view.View.measure(View.java:17915)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5698)
       at android.widget.FrameLayout.onMeasure(FrameLayout.java:465)
       at com.android.internal.policy.impl.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:2728)
       at android.view.View.measure(View.java:17915)
       at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2412)
       at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1414)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1638)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1292)
       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6598)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:800)
       at android.view.Choreographer.doCallbacks(Choreographer.java:603)
       at android.view.Choreographer.doFrame(Choreographer.java:572)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:786)
       at android.os.Handler.handleCallback(Handler.java:815)
       at android.os.Handler.dispatchMessage(Handler.java:104)
       at android.os.Looper.loop(Looper.java:194)
       at android.app.ActivityThread.main(ActivityThread.java:5637)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:959)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:754)
```

Do you have any solution ? Did you check the @by-syk answer and implement his fix ?

Thanks in advance :)

**Comment by PhilippeBoisney** [comment] 2017-02-23 14:38
Oh and this is how I implemented the SearchView on my app, if it can help :
```
//Create search view
if (searchView != null) {
   SearchAdapterOverride searchAdapter = new SearchAdapterOverride(context, list);
   searchAdapter.addOnItemClickListener(new SearchAdapterOverride.OnItemClickListener() {
      @Override
       public void onItemClick(View view, int position) {
          TextView textView = (TextView) view.findViewById(R.id.textView_item_text);
           String query = textView.getText().toString();
           searchView.setQuery(query, false);
           searchView.close(false);
       }
   });
   
   searchView.setTextOnly(previousQuery);
   searchView.setVoice(false);
   if (searchView.getAdapter() == null){
      searchView.setAdapter(searchAdapter);
   }
}
```

**Comment by oleynikd** [comment] 2017-02-27 15:15
Having the same issue

**Comment by jorgeayalaf** [comment] 2017-03-03 00:23
What is the exact line of code that throw the error?
I guess you are modifying the suggestion list data in your customized adapter and you are updating this to the searchview in a incorrect way.

I had the same issue and I solved by updating my suggestion list in the onQueryTextChange method this way:

`                @Override
                public boolean onQueryTextChange(final String newText) {

                    SuggestionResultsAdapter.findSuggestions(newText, new SuggestionResultsAdapter.OnFindSuggestionsListener() {
                                @Override
                                public void onResults(List<Suggestion> results) {
                                    List<SearchItem> mSuggestionsList = new ArrayList<>();

                                    for (Suggestion mSuggestion : results) {
                                        mSuggestionsList.add(new SearchItem(mSuggestion.getBody()));
                                    }

                                    mSearchAdapter.setSuggestionsList(mSuggestionsList);
                                    mSearchAdapter.getFilter().filter(newText);
                                }
                            }
                    );
                    return false;
                }
`

**Comment by PhilippeBoisney** [comment] 2017-03-03 07:43
@jorgeayalaf I can't figure out which line throws this error (See the stacktrace above).
To fix the problem, your solution is to update "suggestion list" every time an user searching ? I will try that 👍

**Comment by PhilippeBoisney** [comment] 2017-03-03 07:55
@jorgeayalaf I tried your solution, but don't seems to work... Actually it triggers the problem more often =/

**Comment by lapism** [comment] 2017-03-03 09:28
Guys , I am so sorry but you have to wait because I do not have time right now...job and family, you know.

**Comment by PhilippeBoisney** [comment] 2017-03-03 09:31
No problem @lapism ! I know what it is ;) The bug are minor and there is
only a few devices affected in my case, so I can wait :)

**Comment by TRiddle** [comment] 2017-03-04 20:21
Is SearchAdapter the only kind of adapter that should be used with this project? Are generic or custom adapters discouraged? btw, I'm getting this error as well.

**Comment by apMadden** [comment] 2017-03-15 22:52
I am getting this error only on one particular Nexus 5X. It runs fine on other devices and even other Nexus 5X's. The logs show no information on where the crash occurs, but the user is saying it happens as soon as he taps the `SearchView`.

**Comment by apMadden** [comment] 2017-03-15 23:21
@PhilippeBoisney You said the issue resurfaced a lot in your app, could you tell me what percentage of users are being affected? 

I'm still using this in the beta phase and have tested on just over 30 devices, but only one guy is getting the crash. He is an edge case user who shuts down basically all permissions and google services so I was assuming I could ignore it. But seeing this issue has me worried to release to production now.

**Comment by PhilippeBoisney** [comment] 2017-03-16 07:21
@apMadden For now, It represents maybe 0,05% of crashs. It happens when user using very quickly the search view and I supposed (not sure) crashs are mainly on slow devices.

**Comment by AllanWang** [comment] 2017-03-24 06:31
The issue seems to occur to me when I load suggestions that fill past the screen and try to scroll. Not sure if that has anything to do with the view bindings

**Comment by wouterdevos** [comment] 2017-04-06 13:45
I have the same issue. I've been testing SearchView with a very basic implementation. All I do is add SearchView to my layout and create a SearchAdapter with some SearchItem's. I get this error when the device orientation changes.

**Comment by apMadden** [comment] 2017-04-06 13:53
@wouterdevos I still sometimes get the error and the Activity I use this in is forced to Portrait. 

Not that this helps you at all, just laying down more info.

**Comment by wouterdevos** [comment] 2017-04-06 14:07
@apMadden Thanks for the additional information. I thought I would mention that it happens on orientation change because that way it could be reliably reproduced.

**Comment by wouterdevos** [comment] 2017-04-06 14:26
After some testing I discovered that I no longer get this error on orientation change if I use my own adapter. I also found [this](http://stackoverflow.com/questions/30693821/fragment-with-recyclerview-java-lang-illegalargumentexception-scrapped-or-att) question on StackOverflow which deals with the same problem. The answer to that question mentions that the issue arose from complications surrounding the use of ORMlite. I noticed that there is a SearchHistoryTable inside the SearchAdapter which deals with database operations. If this issue is in any way related to that post, then this might be a good place to start looking.

**Comment by Veeresh8** [comment] 2017-04-08 18:34
Has anyone found a solution to this?

**Comment by apMadden** [comment] 2017-04-08 18:38
@veeresh nada yet. but My build has been in production for only about a
week and still haven't gotten a single crash report from this case.

Fingers crossed

**Comment by raviganwal** [comment] 2017-04-14 10:06
I faced this issue in latest version, so i used an older version i had and it worked just fine.

**Comment by macci10** [comment] 2017-04-25 11:10
Has anyone solved this issue or found any workaround?

**Comment by apMadden** [comment] 2017-04-25 11:28
@macci10 not yet but I haven't seen any crash reports since release. It only happens in isolated cases as far as I can tell.

**Comment by macci10** [comment] 2017-04-25 11:40
I just revised the code and realized that i have been calling adapter.notifyDataSetChanged() without any purpose and the issue is gone. :) otherwise it was crashing with this exception.

**Comment by Heromine** [comment] 2017-05-18 14:59
same error here...

**Comment by iballan** [comment] 2017-05-31 16:38
I am still getting the same error. i tried all Stackoverflow solutions. is there any news about the issue ? @lapism

**Comment by lapism** [comment] 2017-05-31 16:41
I am working on version 5.0 so I will see if it is gonna happen again.

**Comment by lapism** [comment] 2017-06-10 18:51
I think you should wait untill 5.0 will be released ;)

**Comment by coder3101** [comment] 2017-06-11 07:38
When is the 5.0 scheduled to be released? I mean an approximation!!!

**Comment by boswelja** [comment] 2017-06-11 07:44
@coder3101 when @lapism feels it is ready.. Until then, you'll have to try find another solution

**Comment by lapism** [comment] 2017-06-11 20:46
exactly... you know , work and family ....

**Comment by iballan** [comment] 2017-06-12 08:53
@coder3101 @Heromine @macci10 @apMadden 

Since the problem mostly because of the RecyclerView layout transition animation. I set it to null all the time.

I have this temporary solution working for me. 

```Java
public class MySearchView extends SearchView {

    public MySearchView(Context context) {
        super(context);
        init(context);
    }

    public MySearchView(Context context, @Nullable AttributeSet attrs) {
        super(context, attrs);
        init(context);
    }

    public MySearchView(Context context, @Nullable AttributeSet attrs, int defStyleAttr) {
        super(context, attrs, defStyleAttr);
        init(context);
    }

    public MySearchView(Context context, @Nullable AttributeSet attrs, int defStyleAttr, int defStyleRes) {
        super(context, attrs, defStyleAttr, defStyleRes);
        init(context);
    }

    private void init(Context context) {
        mRecyclerView.setLayoutTransition(null);
        mRecyclerView.setLayoutManager(new ALinearLayoutManager(context));
        mRecyclerView.setFocusableInTouchMode(true);
        setArrowOnly(true);
        setVoice(true);
        setShouldHideOnKeyboardClose(true);
        setShouldClearOnOpen(true);
        setShouldClearOnClose(true);
    }

    @Override
    public void open(boolean animate) {
        super.open(animate);
        setVisibility(VISIBLE);
        mRecyclerView.setLayoutTransition(null);
        mSearchEditText.setText("");
    }

    @Override
    public void close(boolean animate) {
        super.close(animate);
        setVisibility(GONE);
        mRecyclerView.setLayoutTransition(null);
    }

    @Override
    public void setAdapter(RecyclerView.Adapter adapter) {
        try {
            super.setAdapter(adapter);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
}

```

I took **[ALinearLayoutManager](https://github.com/iballan/hfradapter/blob/master/hfradapter/src/main/java/com/mbh/hfradapter/ALinearLayoutManager.java)** from this Library **[HFRAdapter](https://github.com/iballan/hfradapter)**

@lapism you may release a quick fix for the RecyclerView transition before the version 5 release.

**Comment by PhilippeBoisney** [comment] 2017-06-15 06:48
@iballan I've tested your solution but it unfortunately doesn't work on my Samsung : The behavior of Searchview gets strange... However, I've modified your solution to fit this [stackoverflow response](https://stackoverflow.com/questions/26477660/recyclerview-crashes-when-scrapped-or-attached-views-may-not-be-recycled ) : 

```
public class CustomSearchView extends com.lapism.searchview.SearchView {

    public CustomSearchView(Context context) {
        super(context);
        init(context);
    }

    public CustomSearchView(Context context, @Nullable AttributeSet attrs) {
        super(context, attrs);
        init(context);
    }

    public CustomSearchView(Context context, @Nullable AttributeSet attrs, int defStyleAttr) {
        super(context, attrs, defStyleAttr);
        init(context);
    }

    public CustomSearchView(Context context, @Nullable AttributeSet attrs, int defStyleAttr, int defStyleRes) {
        super(context, attrs, defStyleAttr, defStyleRes);
        init(context);
    }

    private void init(Context context) {
        mRecyclerView.setLayoutTransition(null);
        mRecyclerView.setFocusableInTouchMode(true);
    }
}
```
Then in XML:

```
<com.example.package.CustomSearchView
            android:id="@+id/searchView"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            app:layout_behavior="com.lapism.searchview.SearchBehavior" />
```

I'll deploy this fix in production and see if bug disappears. I will keep you informed of result.

**Comment by gbirk** [comment] 2017-06-15 15:21
@PhilippeBoisney your custom class seems to be working for me. Thanks. I'll keep testing.

**Comment by PhilippeBoisney** [comment] 2017-06-23 06:54
It's been two weeks now and the bug not appears anymore ;) So @lapism you can add this fix on your next release !

**Comment by AllanWang** [comment] 2017-06-23 06:56
@PhilippeBoisney do you still have animations though when items are added? The search view should expand naturally rather than blink.

**Comment by PhilippeBoisney** [comment] 2017-06-23 07:01
@AllanWang Unfortunately you're right, with this "quick fix", expand animation is disable.. =/ But app doesn't crash anymore so...

**Comment by lapism** [comment] 2017-06-23 07:06
Transition is already removed from codebase. But I am waiting for more time to finish release 5.0.

**Comment by AllanWang** [comment] 2017-06-23 07:07
@lapism are you deciding to remove the transitions altogether? I was going to recommend delegating the adapter logic to a library such as FastAdapter so you can have more control over the items (click events, long press, filtering, etc) as well as the animations.

**Comment by coder3101** [comment] 2017-06-23 08:31
The Suggestion are no longer appearing with a transition but the bug / crash is fixed..

**Comment by AllanWang** [comment] 2017-06-25 02:08
@lapism I took the liberty today to [rewrite the SearchView in Kotlin](https://github.com/AllanWang/KAU/blob/master/library/src/main/kotlin/ca/allanwang/kau/searchview/SearchView.kt). I'm not sure why there would be an animation bug in yours but you're welcome to pick out whatever you need from this build. I will also look into writing the layouts using constraints since that was something you were looking into as well.

![giphy](https://user-images.githubusercontent.com/6251823/27513153-306ab878-5910-11e7-8ec4-e4c704b1c67c.gif)

**Comment by caka2604** [comment] 2017-07-04 06:43
My solution: 
mAdapter.setHasStableIds(true);

Override getItemId my adapter:
@Override 
public long getItemId(int position) {
        return position;
}

**Comment by vinz243** [comment] 2018-01-01 21:33
@caka2604 the true MVP!

**Closed** 2018-03-29 20:22 UTC
